server:
  port: ${PORT:8080}
app:
  base_url: https://phimhayyy.onrender.com
  limit_size: 20
spring:
  spring:
    main:
      lazy-initialization: true
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql=true: true
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
  mvc:
    servlet:
      path: /api
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 150MB
  application:
    name: jwt-cookie-auth
  session:
    cookie:
      http-only: true
      secure: false
      same-site: none
debug: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    root: INFO
jwt:
  signerKey: ${signerKey}
cloudinary:
  cloud_name: ${cloud_name}
  api_key: ${api_key}
  api_secret: ${api_secret}
